package com.pricepulse.viewmodel;

public enum SettingsEvent {
    UPDATE_SUCCEEDED,
    UPDATE_FAILED,
    EMAIL_UPDATED,
    EMAIL_UPDATE_FAILED,
    PASSWORD_UPDATED,
    PASSWORD_UPDATE_FAILED,
    REAUTH_REQUIRED,
    ADDRESS_SAVED,
    ADDRESS_SAVE_FAILED,
    ADDRESS_DELETED,
    ADDRESS_DELETE_FAILED,
    DEFAULT_ADDRESS_UPDATED,
    DEFAULT_ADDRESS_UPDATE_FAILED
}
